---
driver:
  name: docker
  binary: docker 2>/dev/null

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[mozilla-firefox::default]
    attributes:
